export type PlayerInput = {
  id?: string | number;
  name?: string;
  player_name?: string;
  full_name?: string;
  position?: string;
  isRookie?: boolean;
  projected_points?: number | string;
  projectedPoints?: number | string;
  points?: number | string;
  adp?: number | string;
  avg_adp?: number | string;
  earlySeasonPoints?: number | string;
  early_season_points?: number | string;
  week1Points?: number | string;
  week2Points?: number | string;
  week3Points?: number | string;
  week4Points?: number | string;
  week_1_points?: number | string;
  week_2_points?: number | string;
  week_3_points?: number | string;
  week_4_points?: number | string;
  bye_week?: number | string;
  byeWeek?: number | string;
  std_dev?: number | string;
  best?: number | string;
  worst?: number | string;
  [key: string]: unknown;
};

export type DashboardPlayer = {
  id: string;
  name: string;
  position: string;
  isRookie: boolean;
  projectedPoints: number;
  earlySeasonPoints: number | null;
  week1Points: number | null;
  week2Points: number | null;
  week3Points: number | null;
  week4Points: number | null;
  adp: number | null;
  customValueScore: number;
  overallRank: number | null;
  injuryStatus: string | null;
  byeWeek: number | null;
  stdDev: number | null;
  best: number | null;
  worst: number | null;
  raw: PlayerInput;
};
